// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPGQQBM0OXEYC8XLOMzrNHyct00Pvs-PA',
    appId: '1:325136993258:web:429ca200628b98ad7a8093',
    messagingSenderId: '325136993258',
    projectId: 'entaobora',
    authDomain: 'entaobora.firebaseapp.com',
    storageBucket: 'entaobora.firebasestorage.app',
    measurementId: 'G-NM2W64K39H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3Yeib8gdpIy2GArKUwGWRRmvoMQ8m9zQ',
    appId: '1:325136993258:android:3e0bc80d783658957a8093',
    messagingSenderId: '325136993258',
    projectId: 'entaobora',
    storageBucket: 'entaobora.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ1Invnde0grfRQd2AGJxStLRWWBw80Ic',
    appId: '1:325136993258:ios:f814573ebb347d497a8093',
    messagingSenderId: '325136993258',
    projectId: 'entaobora',
    storageBucket: 'entaobora.firebasestorage.app',
    iosBundleId: 'com.marysoarez.entaobora.entaoBora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ1Invnde0grfRQd2AGJxStLRWWBw80Ic',
    appId: '1:325136993258:ios:f814573ebb347d497a8093',
    messagingSenderId: '325136993258',
    projectId: 'entaobora',
    storageBucket: 'entaobora.firebasestorage.app',
    iosBundleId: 'com.marysoarez.entaobora.entaoBora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPGQQBM0OXEYC8XLOMzrNHyct00Pvs-PA',
    appId: '1:325136993258:web:1226768fbfc7b8de7a8093',
    messagingSenderId: '325136993258',
    projectId: 'entaobora',
    authDomain: 'entaobora.firebaseapp.com',
    storageBucket: 'entaobora.firebasestorage.app',
    measurementId: 'G-CB47E3H31H',
  );
}
